test: Write tests for Checkbox component
featherweight-design/component-library pull request #93
Opened 2021-02-25 00:13 UTC by Tristan-Holtz

## Description

Tests written for checkbox component

- Issues:
  - Resolves #77 

## Changes

- Added checkbox copy object in to checkbox stories

## Sanity Checks

- [x] There are no incidental style changes

2021-02-25 15:14 UTC, HartiganHM commented
@Tristan-Holtz Updated the PR description to name the component explicitly. It's a little redundant to have "write tests" in the description and changes, but it's what I've been doing, so I updated it to be consistent.

It looks like all of the `Checkbox` tests are passing though! Is this ready to be merged in?

2021-02-25 15:21 UTC, HartiganHM requested changes
Overall, all the tests look great and they're passing in the pipeline 🎉 

There are a few small language/organization updates, but once those are in, we should be set!

2021-02-25 15:21 UTC, HartiganHM commented on .github/workflows/pull_request.yml
> +      VERSION: ''
We might have conflicting Prettier configs here. I'll have to double check.

2021-02-25 15:21 UTC, HartiganHM commented on src/cypress/integration/Form/Checkbox/checkbox-disabled.spec.ts
> +describe('checkbox-disabled-test', () => {
Let's update this to the way you have it in the `checkbox-default` tests. It should read: "Checkbox Disabled tests".

2021-02-25 15:21 UTC, HartiganHM commented on src/cypress/integration/Form/Checkbox/checkbox-disabled.spec.ts
> +  it('Should be checked', () => {
Let's update these to be more specific. Something like:
* Should have both options disabled
* Should not have the first option checked
* Should have the second option checked

2021-02-25 15:21 UTC, HartiganHM commented on src/cypress/integration/Form/Checkbox/checkbox-error.spec.ts
> +describe('checkbox-error-tests', () => {
Let's update this describe block too.

2021-02-25 15:21 UTC, HartiganHM commented on src/cypress/integration/Form/Checkbox/checkbox-with-other-options.spec.ts
> +describe('checkbox-with-other-options-tests', () => {
Same here.

2021-02-25 15:21 UTC, HartiganHM commented on src/cypress/integration/Form/Checkbox/checkbox-with-other-options.spec.ts
> +  });
Can you just leave a comment in here to update these once the `Checkbox` and `OtherOption` components are refactored? Something like:

```javascript
// TODO: Update to use findByLabel when Checkbox/OtherOption are refactored
```

This just helps to remind us to update it at some point, outside of the issue we made.

2021-02-25 15:21 UTC, HartiganHM commented on src/shared/data/copyContent/checkboxCopy.ts
> +  cookieDough: 'Cookie Dough',
Alphabetize please 🙃

2021-03-01 22:41 UTC, Tristan-Holtz commented on src/cypress/integration/Form/Checkbox/checkbox-error.spec.ts
> +describe('checkbox-error-tests', () => {
Got it

2021-03-03 02:04 UTC, HartiganHM submitted a review, later dismissed
I went ahead and added those `TODO` notes to the "other option" tests and reverted the single-quotes to double-quotes in the `pull_request.yml`. That must be a Prettier misconfiguration on your machine, so we'll dive into that next.

All of the tests look great though! Excited to get these running in the pipeline and move on to the next one 🎉

2021-03-03 02:22 UTC, HartiganHM approved these changes

2021-03-03 02:22 UTC, merged